/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.api.errors;

import com.anduril.api.core.LatticeApiException;
import okhttp3.Response;

public final class ContentTooLargeError extends LatticeApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Object body;

    public ContentTooLargeError(Object body) {
        super("ContentTooLargeError", 413, body);
        this.body = body;
    }

    public ContentTooLargeError(Object body, Response rawResponse) {
        super("ContentTooLargeError", 413, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Object body() {
        return this.body;
    }
}
