// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/blobs/v1/filter.pub.proto

// Protobuf Java Version: 3.25.3
package com.anduril.blobs.v1;

public interface FieldMatcherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:anduril.blobs.v1.FieldMatcher)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string integration_name = 1 [json_name = "integrationName"];</code>
   * @return The integrationName.
   */
  java.lang.String getIntegrationName();
  /**
   * <code>string integration_name = 1 [json_name = "integrationName"];</code>
   * @return The bytes for integrationName.
   */
  com.google.protobuf.ByteString
      getIntegrationNameBytes();

  /**
   * <code>string mime_type = 2 [json_name = "mimeType"];</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <code>string mime_type = 2 [json_name = "mimeType"];</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();

  /**
   * <code>string data_type = 3 [json_name = "dataType"];</code>
   * @return The dataType.
   */
  java.lang.String getDataType();
  /**
   * <code>string data_type = 3 [json_name = "dataType"];</code>
   * @return The bytes for dataType.
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();
}
