// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/blobs/v1/blobs_api.pub.proto

// Protobuf Java Version: 3.25.3
package com.anduril.blobs.v1;

public interface HeadBlobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:anduril.blobs.v1.HeadBlobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.anduril.blobs.v1.BlobMetadata metadata = 1 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.anduril.blobs.v1.BlobMetadata metadata = 1 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  com.anduril.blobs.v1.BlobMetadata getMetadata();
  /**
   * <code>.anduril.blobs.v1.BlobMetadata metadata = 1 [json_name = "metadata"];</code>
   */
  com.anduril.blobs.v1.BlobMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * URL at which the blob can be fetched
   * </pre>
   *
   * <code>string url = 2 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * URL at which the blob can be fetched
   * </pre>
   *
   * <code>string url = 2 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
