// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/taskmanager/v1/task_api.pub.proto

package com.anduril.taskmanager.v1;

public interface CompleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:anduril.taskmanager.v1.CompleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the task to complete.
   * </pre>
   *
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * ID of the task to complete.
   * </pre>
   *
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();
}
