// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/taskmanager/v1/task.pub.proto

package com.anduril.taskmanager.v1;

public interface OwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:anduril.taskmanager.v1.Owner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Entity ID of the owner.
   * </pre>
   *
   * <code>string entity_id = 2 [json_name = "entityId"];</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <pre>
   * Entity ID of the owner.
   * </pre>
   *
   * <code>string entity_id = 2 [json_name = "entityId"];</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();
}
