// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/taskmanager/v1/task_manager_api.pub.proto
// Protobuf Java Version: 4.27.3

package com.anduril.taskmanager.v1;

public final class TaskManagerApiPubProto {
  private TaskManagerApiPubProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      TaskManagerApiPubProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_CreateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_CreateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_CreateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_CreateTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_GetTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_GetTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_GetTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_GetTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_UpdateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_UpdateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_UpdateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_UpdateTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_UpdateStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_UpdateStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_UpdateStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_UpdateStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_StreamTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_StreamTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_StreamTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_StreamTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_RateLimit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_RateLimit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_taskmanager_v1_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_taskmanager_v1_Heartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1anduril/taskmanager/v1/task_manager_ap" +
      "i.pub.proto\022\026anduril.taskmanager.v1\032%and" +
      "uril/taskmanager/v1/task.pub.proto\032\031goog" +
      "le/protobuf/any.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\270\003\n\021CreateTaskRequest\022!\n\014" +
      "display_name\030\001 \001(\tR\013displayName\022:\n\rspeci" +
      "fication\030\002 \001(\0132\024.google.protobuf.AnyR\rsp" +
      "ecification\0229\n\006author\030\003 \001(\0132!.anduril.ta" +
      "skmanager.v1.PrincipalR\006author\022?\n\trelati" +
      "ons\030\005 \001(\0132!.anduril.taskmanager.v1.Relat" +
      "ionsR\trelations\022 \n\013description\030\006 \001(\tR\013de" +
      "scription\0222\n\025is_executed_elsewhere\030\007 \001(\010" +
      "R\023isExecutedElsewhere\022\027\n\007task_id\030\010 \001(\tR\006" +
      "taskId\022M\n\020initial_entities\030\t \003(\0132\".andur" +
      "il.taskmanager.v1.TaskEntityR\017initialEnt" +
      "itiesJ\004\010\004\020\005J\004\010\n\020\013\"F\n\022CreateTaskResponse\022" +
      "0\n\004task\030\001 \001(\0132\034.anduril.taskmanager.v1.T" +
      "askR\004task\"\227\001\n\016GetTaskRequest\022\027\n\007task_id\030" +
      "\001 \001(\tR\006taskId\022-\n\022definition_version\030\002 \001(" +
      "\rR\021definitionVersion\022=\n\ttask_view\030\003 \001(\0162" +
      " .anduril.taskmanager.v1.TaskViewR\010taskV" +
      "iew\"C\n\017GetTaskResponse\0220\n\004task\030\001 \001(\0132\034.a" +
      "nduril.taskmanager.v1.TaskR\004task\"y\n\021Upda" +
      "teTaskRequest\0220\n\004task\030\001 \001(\0132\034.anduril.ta" +
      "skmanager.v1.TaskR\004task\0222\n\025is_executed_e" +
      "lsewhere\030\007 \001(\010R\023isExecutedElsewhere\"F\n\022U" +
      "pdateTaskResponse\0220\n\004task\030\001 \001(\0132\034.anduri" +
      "l.taskmanager.v1.TaskR\004task\"`\n\023UpdateSta" +
      "tusRequest\022I\n\rstatus_update\030\001 \001(\0132$.andu" +
      "ril.taskmanager.v1.StatusUpdateR\014statusU" +
      "pdate\"H\n\024UpdateStatusResponse\0220\n\004task\030\001 " +
      "\001(\0132\034.anduril.taskmanager.v1.TaskR\004task\"" +
      "\306\001\n\022StreamTasksRequest\022@\n\nrate_limit\030\001 \001" +
      "(\0132!.anduril.taskmanager.v1.RateLimitR\tr" +
      "ateLimit\0226\n\005views\030\002 \003(\0162 .anduril.taskma" +
      "nager.v1.TaskViewR\005views\0226\n\027heartbeat_pe" +
      "riod_millis\030\003 \001(\rR\025heartbeatPeriodMillis" +
      "\"\230\001\n\023StreamTasksResponse\022@\n\ntask_event\030\001" +
      " \001(\0132!.anduril.taskmanager.v1.TaskEventR" +
      "\ttaskEvent\022?\n\theartbeat\030\002 \001(\0132!.anduril." +
      "taskmanager.v1.HeartbeatR\theartbeat\"C\n\tR" +
      "ateLimit\0226\n\030update_per_task_limit_ms\030\001 \001" +
      "(\rR\024updatePerTaskLimitMs\"E\n\tHeartbeat\0228\n" +
      "\ttimestamp\030\001 \001(\0132\032.google.protobuf.Times" +
      "tampR\ttimestamp2\213\004\n\016TaskManagerAPI\022c\n\nCr" +
      "eateTask\022).anduril.taskmanager.v1.Create" +
      "TaskRequest\032*.anduril.taskmanager.v1.Cre" +
      "ateTaskResponse\022Z\n\007GetTask\022&.anduril.tas" +
      "kmanager.v1.GetTaskRequest\032\'.anduril.tas" +
      "kmanager.v1.GetTaskResponse\022c\n\nUpdateTas" +
      "k\022).anduril.taskmanager.v1.UpdateTaskReq" +
      "uest\032*.anduril.taskmanager.v1.UpdateTask" +
      "Response\022i\n\014UpdateStatus\022+.anduril.taskm" +
      "anager.v1.UpdateStatusRequest\032,.anduril." +
      "taskmanager.v1.UpdateStatusResponse\022h\n\013S" +
      "treamTasks\022*.anduril.taskmanager.v1.Stre" +
      "amTasksRequest\032+.anduril.taskmanager.v1." +
      "StreamTasksResponse0\001B\200\002\n\032com.anduril.ta" +
      "skmanager.v1B\026TaskManagerApiPubProtoP\001ZP" +
      "github.com/dogun-anduril/anduril-sdk-go/" +
      "src/anduril/taskmanager/v1;taskmanagerv1" +
      "\242\002\003ATX\252\002\026Anduril.Taskmanager.V1\312\002\026Anduri" +
      "l\\Taskmanager\\V1\342\002\"Anduril\\Taskmanager\\V" +
      "1\\GPBMetadata\352\002\030Anduril::Taskmanager::V1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.anduril.taskmanager.v1.TaskPubProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_anduril_taskmanager_v1_CreateTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_anduril_taskmanager_v1_CreateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_CreateTaskRequest_descriptor,
        new java.lang.String[] { "DisplayName", "Specification", "Author", "Relations", "Description", "IsExecutedElsewhere", "TaskId", "InitialEntities", });
    internal_static_anduril_taskmanager_v1_CreateTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_anduril_taskmanager_v1_CreateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_CreateTaskResponse_descriptor,
        new java.lang.String[] { "Task", });
    internal_static_anduril_taskmanager_v1_GetTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_anduril_taskmanager_v1_GetTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_GetTaskRequest_descriptor,
        new java.lang.String[] { "TaskId", "DefinitionVersion", "TaskView", });
    internal_static_anduril_taskmanager_v1_GetTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_anduril_taskmanager_v1_GetTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_GetTaskResponse_descriptor,
        new java.lang.String[] { "Task", });
    internal_static_anduril_taskmanager_v1_UpdateTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_anduril_taskmanager_v1_UpdateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_UpdateTaskRequest_descriptor,
        new java.lang.String[] { "Task", "IsExecutedElsewhere", });
    internal_static_anduril_taskmanager_v1_UpdateTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_anduril_taskmanager_v1_UpdateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_UpdateTaskResponse_descriptor,
        new java.lang.String[] { "Task", });
    internal_static_anduril_taskmanager_v1_UpdateStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_anduril_taskmanager_v1_UpdateStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_UpdateStatusRequest_descriptor,
        new java.lang.String[] { "StatusUpdate", });
    internal_static_anduril_taskmanager_v1_UpdateStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_anduril_taskmanager_v1_UpdateStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_UpdateStatusResponse_descriptor,
        new java.lang.String[] { "Task", });
    internal_static_anduril_taskmanager_v1_StreamTasksRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_anduril_taskmanager_v1_StreamTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_StreamTasksRequest_descriptor,
        new java.lang.String[] { "RateLimit", "Views", "HeartbeatPeriodMillis", });
    internal_static_anduril_taskmanager_v1_StreamTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_anduril_taskmanager_v1_StreamTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_StreamTasksResponse_descriptor,
        new java.lang.String[] { "TaskEvent", "Heartbeat", });
    internal_static_anduril_taskmanager_v1_RateLimit_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_anduril_taskmanager_v1_RateLimit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_RateLimit_descriptor,
        new java.lang.String[] { "UpdatePerTaskLimitMs", });
    internal_static_anduril_taskmanager_v1_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_anduril_taskmanager_v1_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_taskmanager_v1_Heartbeat_descriptor,
        new java.lang.String[] { "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
    com.anduril.taskmanager.v1.TaskPubProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
