// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/communicationsmanager/v1/common.pub.proto
// Protobuf Java Version: 4.27.3

package com.anduril.communicationsmanager.v1;

/**
 * <pre>
 * A destination to which data are routed.
 * </pre>
 *
 * Protobuf type {@code anduril.communicationsmanager.v1.Destination}
 */
public final class Destination extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:anduril.communicationsmanager.v1.Destination)
    DestinationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      Destination.class.getName());
  }
  // Use Destination.newBuilder() to construct.
  private Destination(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Destination() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.anduril.communicationsmanager.v1.CommonPubProto.internal_static_anduril_communicationsmanager_v1_Destination_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.anduril.communicationsmanager.v1.CommonPubProto.internal_static_anduril_communicationsmanager_v1_Destination_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.anduril.communicationsmanager.v1.Destination.class, com.anduril.communicationsmanager.v1.Destination.Builder.class);
  }

  private int destinationCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object destination_;
  public enum DestinationCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    @java.lang.Deprecated ASSET_ID(1),
    HOST_ID(2),
    ALL(3),
    DESTINATION_NOT_SET(0);
    private final int value;
    private DestinationCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DestinationCase valueOf(int value) {
      return forNumber(value);
    }

    public static DestinationCase forNumber(int value) {
      switch (value) {
        case 1: return ASSET_ID;
        case 2: return HOST_ID;
        case 3: return ALL;
        case 0: return DESTINATION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DestinationCase
  getDestinationCase() {
    return DestinationCase.forNumber(
        destinationCase_);
  }

  public static final int ASSET_ID_FIELD_NUMBER = 1;
  /**
   * <pre>
   * The destination is a particular asset ID.
   * </pre>
   *
   * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
   * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
   *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
   * @return Whether the assetId field is set.
   */
  @java.lang.Deprecated public boolean hasAssetId() {
    return destinationCase_ == 1;
  }
  /**
   * <pre>
   * The destination is a particular asset ID.
   * </pre>
   *
   * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
   * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
   *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
   * @return The assetId.
   */
  @java.lang.Deprecated public java.lang.String getAssetId() {
    java.lang.Object ref = "";
    if (destinationCase_ == 1) {
      ref = destination_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (destinationCase_ == 1) {
        destination_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The destination is a particular asset ID.
   * </pre>
   *
   * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
   * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
   *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
   * @return The bytes for assetId.
   */
  @java.lang.Deprecated public com.google.protobuf.ByteString
      getAssetIdBytes() {
    java.lang.Object ref = "";
    if (destinationCase_ == 1) {
      ref = destination_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (destinationCase_ == 1) {
        destination_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOST_ID_FIELD_NUMBER = 2;
  /**
   * <pre>
   * The destination is a particular host ID.
   * </pre>
   *
   * <code>string host_id = 2 [json_name = "hostId"];</code>
   * @return Whether the hostId field is set.
   */
  public boolean hasHostId() {
    return destinationCase_ == 2;
  }
  /**
   * <pre>
   * The destination is a particular host ID.
   * </pre>
   *
   * <code>string host_id = 2 [json_name = "hostId"];</code>
   * @return The hostId.
   */
  public java.lang.String getHostId() {
    java.lang.Object ref = "";
    if (destinationCase_ == 2) {
      ref = destination_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (destinationCase_ == 2) {
        destination_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The destination is a particular host ID.
   * </pre>
   *
   * <code>string host_id = 2 [json_name = "hostId"];</code>
   * @return The bytes for hostId.
   */
  public com.google.protobuf.ByteString
      getHostIdBytes() {
    java.lang.Object ref = "";
    if (destinationCase_ == 2) {
      ref = destination_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (destinationCase_ == 2) {
        destination_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALL_FIELD_NUMBER = 3;
  /**
   * <pre>
   * The destination is all destinations. This selection is only used for outbound rules.
   * </pre>
   *
   * <code>bool all = 3 [json_name = "all"];</code>
   * @return Whether the all field is set.
   */
  @java.lang.Override
  public boolean hasAll() {
    return destinationCase_ == 3;
  }
  /**
   * <pre>
   * The destination is all destinations. This selection is only used for outbound rules.
   * </pre>
   *
   * <code>bool all = 3 [json_name = "all"];</code>
   * @return The all.
   */
  @java.lang.Override
  public boolean getAll() {
    if (destinationCase_ == 3) {
      return (java.lang.Boolean) destination_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (destinationCase_ == 1) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, destination_);
    }
    if (destinationCase_ == 2) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, destination_);
    }
    if (destinationCase_ == 3) {
      output.writeBool(
          3, (boolean)((java.lang.Boolean) destination_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (destinationCase_ == 1) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, destination_);
    }
    if (destinationCase_ == 2) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, destination_);
    }
    if (destinationCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            3, (boolean)((java.lang.Boolean) destination_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.anduril.communicationsmanager.v1.Destination)) {
      return super.equals(obj);
    }
    com.anduril.communicationsmanager.v1.Destination other = (com.anduril.communicationsmanager.v1.Destination) obj;

    if (!getDestinationCase().equals(other.getDestinationCase())) return false;
    switch (destinationCase_) {
      case 1:
        if (!getAssetId()
            .equals(other.getAssetId())) return false;
        break;
      case 2:
        if (!getHostId()
            .equals(other.getHostId())) return false;
        break;
      case 3:
        if (getAll()
            != other.getAll()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (destinationCase_) {
      case 1:
        hash = (37 * hash) + ASSET_ID_FIELD_NUMBER;
        hash = (53 * hash) + getAssetId().hashCode();
        break;
      case 2:
        hash = (37 * hash) + HOST_ID_FIELD_NUMBER;
        hash = (53 * hash) + getHostId().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ALL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAll());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.anduril.communicationsmanager.v1.Destination parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.anduril.communicationsmanager.v1.Destination parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.communicationsmanager.v1.Destination parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.anduril.communicationsmanager.v1.Destination prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A destination to which data are routed.
   * </pre>
   *
   * Protobuf type {@code anduril.communicationsmanager.v1.Destination}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:anduril.communicationsmanager.v1.Destination)
      com.anduril.communicationsmanager.v1.DestinationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anduril.communicationsmanager.v1.CommonPubProto.internal_static_anduril_communicationsmanager_v1_Destination_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anduril.communicationsmanager.v1.CommonPubProto.internal_static_anduril_communicationsmanager_v1_Destination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.anduril.communicationsmanager.v1.Destination.class, com.anduril.communicationsmanager.v1.Destination.Builder.class);
    }

    // Construct using com.anduril.communicationsmanager.v1.Destination.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      destinationCase_ = 0;
      destination_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.anduril.communicationsmanager.v1.CommonPubProto.internal_static_anduril_communicationsmanager_v1_Destination_descriptor;
    }

    @java.lang.Override
    public com.anduril.communicationsmanager.v1.Destination getDefaultInstanceForType() {
      return com.anduril.communicationsmanager.v1.Destination.getDefaultInstance();
    }

    @java.lang.Override
    public com.anduril.communicationsmanager.v1.Destination build() {
      com.anduril.communicationsmanager.v1.Destination result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.anduril.communicationsmanager.v1.Destination buildPartial() {
      com.anduril.communicationsmanager.v1.Destination result = new com.anduril.communicationsmanager.v1.Destination(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.anduril.communicationsmanager.v1.Destination result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.anduril.communicationsmanager.v1.Destination result) {
      result.destinationCase_ = destinationCase_;
      result.destination_ = this.destination_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.anduril.communicationsmanager.v1.Destination) {
        return mergeFrom((com.anduril.communicationsmanager.v1.Destination)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.anduril.communicationsmanager.v1.Destination other) {
      if (other == com.anduril.communicationsmanager.v1.Destination.getDefaultInstance()) return this;
      switch (other.getDestinationCase()) {
        case ASSET_ID: {
          destinationCase_ = 1;
          destination_ = other.destination_;
          onChanged();
          break;
        }
        case HOST_ID: {
          destinationCase_ = 2;
          destination_ = other.destination_;
          onChanged();
          break;
        }
        case ALL: {
          setAll(other.getAll());
          break;
        }
        case DESTINATION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              destinationCase_ = 1;
              destination_ = s;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              destinationCase_ = 2;
              destination_ = s;
              break;
            } // case 18
            case 24: {
              destination_ = input.readBool();
              destinationCase_ = 3;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int destinationCase_ = 0;
    private java.lang.Object destination_;
    public DestinationCase
        getDestinationCase() {
      return DestinationCase.forNumber(
          destinationCase_);
    }

    public Builder clearDestination() {
      destinationCase_ = 0;
      destination_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * The destination is a particular asset ID.
     * </pre>
     *
     * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
     * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
     *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
     * @return Whether the assetId field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasAssetId() {
      return destinationCase_ == 1;
    }
    /**
     * <pre>
     * The destination is a particular asset ID.
     * </pre>
     *
     * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
     * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
     *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
     * @return The assetId.
     */
    @java.lang.Override
    @java.lang.Deprecated public java.lang.String getAssetId() {
      java.lang.Object ref = "";
      if (destinationCase_ == 1) {
        ref = destination_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (destinationCase_ == 1) {
          destination_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The destination is a particular asset ID.
     * </pre>
     *
     * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
     * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
     *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
     * @return The bytes for assetId.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = "";
      if (destinationCase_ == 1) {
        ref = destination_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (destinationCase_ == 1) {
          destination_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The destination is a particular asset ID.
     * </pre>
     *
     * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
     * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
     *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
     * @param value The assetId to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setAssetId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationCase_ = 1;
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The destination is a particular asset ID.
     * </pre>
     *
     * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
     * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
     *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearAssetId() {
      if (destinationCase_ == 1) {
        destinationCase_ = 0;
        destination_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The destination is a particular asset ID.
     * </pre>
     *
     * <code>string asset_id = 1 [json_name = "assetId", deprecated = true];</code>
     * @deprecated anduril.communicationsmanager.v1.Destination.asset_id is deprecated.
     *     See anduril/communicationsmanager/v1/common.pub.proto;l=145
     * @param value The bytes for assetId to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setAssetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      destinationCase_ = 1;
      destination_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * The destination is a particular host ID.
     * </pre>
     *
     * <code>string host_id = 2 [json_name = "hostId"];</code>
     * @return Whether the hostId field is set.
     */
    @java.lang.Override
    public boolean hasHostId() {
      return destinationCase_ == 2;
    }
    /**
     * <pre>
     * The destination is a particular host ID.
     * </pre>
     *
     * <code>string host_id = 2 [json_name = "hostId"];</code>
     * @return The hostId.
     */
    @java.lang.Override
    public java.lang.String getHostId() {
      java.lang.Object ref = "";
      if (destinationCase_ == 2) {
        ref = destination_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (destinationCase_ == 2) {
          destination_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The destination is a particular host ID.
     * </pre>
     *
     * <code>string host_id = 2 [json_name = "hostId"];</code>
     * @return The bytes for hostId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostIdBytes() {
      java.lang.Object ref = "";
      if (destinationCase_ == 2) {
        ref = destination_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (destinationCase_ == 2) {
          destination_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The destination is a particular host ID.
     * </pre>
     *
     * <code>string host_id = 2 [json_name = "hostId"];</code>
     * @param value The hostId to set.
     * @return This builder for chaining.
     */
    public Builder setHostId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationCase_ = 2;
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The destination is a particular host ID.
     * </pre>
     *
     * <code>string host_id = 2 [json_name = "hostId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHostId() {
      if (destinationCase_ == 2) {
        destinationCase_ = 0;
        destination_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The destination is a particular host ID.
     * </pre>
     *
     * <code>string host_id = 2 [json_name = "hostId"];</code>
     * @param value The bytes for hostId to set.
     * @return This builder for chaining.
     */
    public Builder setHostIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      destinationCase_ = 2;
      destination_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * The destination is all destinations. This selection is only used for outbound rules.
     * </pre>
     *
     * <code>bool all = 3 [json_name = "all"];</code>
     * @return Whether the all field is set.
     */
    public boolean hasAll() {
      return destinationCase_ == 3;
    }
    /**
     * <pre>
     * The destination is all destinations. This selection is only used for outbound rules.
     * </pre>
     *
     * <code>bool all = 3 [json_name = "all"];</code>
     * @return The all.
     */
    public boolean getAll() {
      if (destinationCase_ == 3) {
        return (java.lang.Boolean) destination_;
      }
      return false;
    }
    /**
     * <pre>
     * The destination is all destinations. This selection is only used for outbound rules.
     * </pre>
     *
     * <code>bool all = 3 [json_name = "all"];</code>
     * @param value The all to set.
     * @return This builder for chaining.
     */
    public Builder setAll(boolean value) {

      destinationCase_ = 3;
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The destination is all destinations. This selection is only used for outbound rules.
     * </pre>
     *
     * <code>bool all = 3 [json_name = "all"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAll() {
      if (destinationCase_ == 3) {
        destinationCase_ = 0;
        destination_ = null;
        onChanged();
      }
      return this;
    }

    // @@protoc_insertion_point(builder_scope:anduril.communicationsmanager.v1.Destination)
  }

  // @@protoc_insertion_point(class_scope:anduril.communicationsmanager.v1.Destination)
  private static final com.anduril.communicationsmanager.v1.Destination DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.anduril.communicationsmanager.v1.Destination();
  }

  public static com.anduril.communicationsmanager.v1.Destination getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Destination>
      PARSER = new com.google.protobuf.AbstractParser<Destination>() {
    @java.lang.Override
    public Destination parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Destination> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Destination> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.anduril.communicationsmanager.v1.Destination getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

