// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/type/coords.pub.proto

package com.anduril.type;

public interface YPROrBuilder extends
    // @@protoc_insertion_point(interface_extends:anduril.type.YPR)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double yaw = 1 [json_name = "yaw"];</code>
   * @return The yaw.
   */
  double getYaw();

  /**
   * <code>double pitch = 2 [json_name = "pitch"];</code>
   * @return The pitch.
   */
  double getPitch();

  /**
   * <code>double roll = 3 [json_name = "roll"];</code>
   * @return The roll.
   */
  double getRoll();
}
