// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/tasks/v2/shared/maneuver.pub.proto

package com.anduril.tasks.v2;

/**
 * <pre>
 * Maps to UCI code RoutePlan.
 * Used to command a platform between locations by requesting to make this RoutePlan the single primary active route.
 * </pre>
 *
 * Protobuf type {@code anduril.tasks.v2.Transit}
 */
public final class Transit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:anduril.tasks.v2.Transit)
    TransitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Transit.newBuilder() to construct.
  private Transit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Transit() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Transit();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.anduril.tasks.v2.ManeuverPubProto.internal_static_anduril_tasks_v2_Transit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.anduril.tasks.v2.ManeuverPubProto.internal_static_anduril_tasks_v2_Transit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.anduril.tasks.v2.Transit.class, com.anduril.tasks.v2.Transit.Builder.class);
  }

  public static final int PLAN_FIELD_NUMBER = 1;
  private com.anduril.tasks.v2.RoutePlan plan_;
  /**
   * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
   * @return Whether the plan field is set.
   */
  @java.lang.Override
  public boolean hasPlan() {
    return plan_ != null;
  }
  /**
   * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
   * @return The plan.
   */
  @java.lang.Override
  public com.anduril.tasks.v2.RoutePlan getPlan() {
    return plan_ == null ? com.anduril.tasks.v2.RoutePlan.getDefaultInstance() : plan_;
  }
  /**
   * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
   */
  @java.lang.Override
  public com.anduril.tasks.v2.RoutePlanOrBuilder getPlanOrBuilder() {
    return plan_ == null ? com.anduril.tasks.v2.RoutePlan.getDefaultInstance() : plan_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (plan_ != null) {
      output.writeMessage(1, getPlan());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (plan_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPlan());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.anduril.tasks.v2.Transit)) {
      return super.equals(obj);
    }
    com.anduril.tasks.v2.Transit other = (com.anduril.tasks.v2.Transit) obj;

    if (hasPlan() != other.hasPlan()) return false;
    if (hasPlan()) {
      if (!getPlan()
          .equals(other.getPlan())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPlan()) {
      hash = (37 * hash) + PLAN_FIELD_NUMBER;
      hash = (53 * hash) + getPlan().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.anduril.tasks.v2.Transit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.tasks.v2.Transit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.anduril.tasks.v2.Transit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.tasks.v2.Transit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.anduril.tasks.v2.Transit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Maps to UCI code RoutePlan.
   * Used to command a platform between locations by requesting to make this RoutePlan the single primary active route.
   * </pre>
   *
   * Protobuf type {@code anduril.tasks.v2.Transit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:anduril.tasks.v2.Transit)
      com.anduril.tasks.v2.TransitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anduril.tasks.v2.ManeuverPubProto.internal_static_anduril_tasks_v2_Transit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anduril.tasks.v2.ManeuverPubProto.internal_static_anduril_tasks_v2_Transit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.anduril.tasks.v2.Transit.class, com.anduril.tasks.v2.Transit.Builder.class);
    }

    // Construct using com.anduril.tasks.v2.Transit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      plan_ = null;
      if (planBuilder_ != null) {
        planBuilder_.dispose();
        planBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.anduril.tasks.v2.ManeuverPubProto.internal_static_anduril_tasks_v2_Transit_descriptor;
    }

    @java.lang.Override
    public com.anduril.tasks.v2.Transit getDefaultInstanceForType() {
      return com.anduril.tasks.v2.Transit.getDefaultInstance();
    }

    @java.lang.Override
    public com.anduril.tasks.v2.Transit build() {
      com.anduril.tasks.v2.Transit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.anduril.tasks.v2.Transit buildPartial() {
      com.anduril.tasks.v2.Transit result = new com.anduril.tasks.v2.Transit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.anduril.tasks.v2.Transit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.plan_ = planBuilder_ == null
            ? plan_
            : planBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.anduril.tasks.v2.Transit) {
        return mergeFrom((com.anduril.tasks.v2.Transit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.anduril.tasks.v2.Transit other) {
      if (other == com.anduril.tasks.v2.Transit.getDefaultInstance()) return this;
      if (other.hasPlan()) {
        mergePlan(other.getPlan());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPlanFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.anduril.tasks.v2.RoutePlan plan_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.anduril.tasks.v2.RoutePlan, com.anduril.tasks.v2.RoutePlan.Builder, com.anduril.tasks.v2.RoutePlanOrBuilder> planBuilder_;
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     * @return Whether the plan field is set.
     */
    public boolean hasPlan() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     * @return The plan.
     */
    public com.anduril.tasks.v2.RoutePlan getPlan() {
      if (planBuilder_ == null) {
        return plan_ == null ? com.anduril.tasks.v2.RoutePlan.getDefaultInstance() : plan_;
      } else {
        return planBuilder_.getMessage();
      }
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    public Builder setPlan(com.anduril.tasks.v2.RoutePlan value) {
      if (planBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        plan_ = value;
      } else {
        planBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    public Builder setPlan(
        com.anduril.tasks.v2.RoutePlan.Builder builderForValue) {
      if (planBuilder_ == null) {
        plan_ = builderForValue.build();
      } else {
        planBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    public Builder mergePlan(com.anduril.tasks.v2.RoutePlan value) {
      if (planBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          plan_ != null &&
          plan_ != com.anduril.tasks.v2.RoutePlan.getDefaultInstance()) {
          getPlanBuilder().mergeFrom(value);
        } else {
          plan_ = value;
        }
      } else {
        planBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    public Builder clearPlan() {
      bitField0_ = (bitField0_ & ~0x00000001);
      plan_ = null;
      if (planBuilder_ != null) {
        planBuilder_.dispose();
        planBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    public com.anduril.tasks.v2.RoutePlan.Builder getPlanBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPlanFieldBuilder().getBuilder();
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    public com.anduril.tasks.v2.RoutePlanOrBuilder getPlanOrBuilder() {
      if (planBuilder_ != null) {
        return planBuilder_.getMessageOrBuilder();
      } else {
        return plan_ == null ?
            com.anduril.tasks.v2.RoutePlan.getDefaultInstance() : plan_;
      }
    }
    /**
     * <code>.anduril.tasks.v2.RoutePlan plan = 1 [json_name = "plan"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.anduril.tasks.v2.RoutePlan, com.anduril.tasks.v2.RoutePlan.Builder, com.anduril.tasks.v2.RoutePlanOrBuilder> 
        getPlanFieldBuilder() {
      if (planBuilder_ == null) {
        planBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.anduril.tasks.v2.RoutePlan, com.anduril.tasks.v2.RoutePlan.Builder, com.anduril.tasks.v2.RoutePlanOrBuilder>(
                getPlan(),
                getParentForChildren(),
                isClean());
        plan_ = null;
      }
      return planBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:anduril.tasks.v2.Transit)
  }

  // @@protoc_insertion_point(class_scope:anduril.tasks.v2.Transit)
  private static final com.anduril.tasks.v2.Transit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.anduril.tasks.v2.Transit();
  }

  public static com.anduril.tasks.v2.Transit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transit>
      PARSER = new com.google.protobuf.AbstractParser<Transit>() {
    @java.lang.Override
    public Transit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Transit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.anduril.tasks.v2.Transit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

