// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/entitymanager/v1/contact_details.pub.proto
// Protobuf Java Version: 4.27.3

package com.anduril.entitymanager.v1;

public final class ContactDetailsPubProto {
  private ContactDetailsPubProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ContactDetailsPubProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anduril_entitymanager_v1_ContactDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anduril_entitymanager_v1_ContactDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2anduril/entitymanager/v1/contact_detai" +
      "ls.pub.proto\022\030anduril.entitymanager.v1\"3" +
      "\n\016ContactDetails\022!\n\014phone_number\030\001 \001(\tR\013" +
      "phoneNumberB\216\002\n\034com.anduril.entitymanage" +
      "r.v1B\026ContactDetailsPubProtoP\001ZTgithub.c" +
      "om/dogun-anduril/anduril-sdk-go/src/andu" +
      "ril/entitymanager/v1;entitymanagerv1\242\002\003A" +
      "EX\252\002\030Anduril.Entitymanager.V1\312\002\030Anduril\\" +
      "Entitymanager\\V1\342\002$Anduril\\Entitymanager" +
      "\\V1\\GPBMetadata\352\002\032Anduril::Entitymanager" +
      "::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_anduril_entitymanager_v1_ContactDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_anduril_entitymanager_v1_ContactDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anduril_entitymanager_v1_ContactDetails_descriptor,
        new java.lang.String[] { "PhoneNumber", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
