// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/entitymanager/v1/geoentity.pub.proto

// Protobuf Java Version: 3.25.3
package com.anduril.entitymanager.v1;

/**
 * <pre>
 * Details specific to displaying a geo-entity
 * </pre>
 *
 * Protobuf type {@code anduril.entitymanager.v1.GeoVisualDetails}
 */
public final class GeoVisualDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:anduril.entitymanager.v1.GeoVisualDetails)
    GeoVisualDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeoVisualDetails.newBuilder() to construct.
  private GeoVisualDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeoVisualDetails() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeoVisualDetails();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.anduril.entitymanager.v1.GeoentityPubProto.internal_static_anduril_entitymanager_v1_GeoVisualDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.anduril.entitymanager.v1.GeoentityPubProto.internal_static_anduril_entitymanager_v1_GeoVisualDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.anduril.entitymanager.v1.GeoVisualDetails.class, com.anduril.entitymanager.v1.GeoVisualDetails.Builder.class);
  }

  private int bitField0_;
  public static final int FILL_COLOR_FIELD_NUMBER = 1;
  private com.anduril.type.Color fillColor_;
  /**
   * <pre>
   *A string describing the fill color of a geo-entity.
   * </pre>
   *
   * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
   * @return Whether the fillColor field is set.
   */
  @java.lang.Override
  public boolean hasFillColor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *A string describing the fill color of a geo-entity.
   * </pre>
   *
   * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
   * @return The fillColor.
   */
  @java.lang.Override
  public com.anduril.type.Color getFillColor() {
    return fillColor_ == null ? com.anduril.type.Color.getDefaultInstance() : fillColor_;
  }
  /**
   * <pre>
   *A string describing the fill color of a geo-entity.
   * </pre>
   *
   * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
   */
  @java.lang.Override
  public com.anduril.type.ColorOrBuilder getFillColorOrBuilder() {
    return fillColor_ == null ? com.anduril.type.Color.getDefaultInstance() : fillColor_;
  }

  public static final int LINE_COLOR_FIELD_NUMBER = 2;
  private com.anduril.type.Color lineColor_;
  /**
   * <pre>
   *A string describing the line color of a geo-entity.
   * </pre>
   *
   * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
   * @return Whether the lineColor field is set.
   */
  @java.lang.Override
  public boolean hasLineColor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   *A string describing the line color of a geo-entity.
   * </pre>
   *
   * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
   * @return The lineColor.
   */
  @java.lang.Override
  public com.anduril.type.Color getLineColor() {
    return lineColor_ == null ? com.anduril.type.Color.getDefaultInstance() : lineColor_;
  }
  /**
   * <pre>
   *A string describing the line color of a geo-entity.
   * </pre>
   *
   * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
   */
  @java.lang.Override
  public com.anduril.type.ColorOrBuilder getLineColorOrBuilder() {
    return lineColor_ == null ? com.anduril.type.Color.getDefaultInstance() : lineColor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getFillColor());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getLineColor());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFillColor());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLineColor());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.anduril.entitymanager.v1.GeoVisualDetails)) {
      return super.equals(obj);
    }
    com.anduril.entitymanager.v1.GeoVisualDetails other = (com.anduril.entitymanager.v1.GeoVisualDetails) obj;

    if (hasFillColor() != other.hasFillColor()) return false;
    if (hasFillColor()) {
      if (!getFillColor()
          .equals(other.getFillColor())) return false;
    }
    if (hasLineColor() != other.hasLineColor()) return false;
    if (hasLineColor()) {
      if (!getLineColor()
          .equals(other.getLineColor())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFillColor()) {
      hash = (37 * hash) + FILL_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getFillColor().hashCode();
    }
    if (hasLineColor()) {
      hash = (37 * hash) + LINE_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getLineColor().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.anduril.entitymanager.v1.GeoVisualDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.anduril.entitymanager.v1.GeoVisualDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.GeoVisualDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.anduril.entitymanager.v1.GeoVisualDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Details specific to displaying a geo-entity
   * </pre>
   *
   * Protobuf type {@code anduril.entitymanager.v1.GeoVisualDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:anduril.entitymanager.v1.GeoVisualDetails)
      com.anduril.entitymanager.v1.GeoVisualDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anduril.entitymanager.v1.GeoentityPubProto.internal_static_anduril_entitymanager_v1_GeoVisualDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anduril.entitymanager.v1.GeoentityPubProto.internal_static_anduril_entitymanager_v1_GeoVisualDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.anduril.entitymanager.v1.GeoVisualDetails.class, com.anduril.entitymanager.v1.GeoVisualDetails.Builder.class);
    }

    // Construct using com.anduril.entitymanager.v1.GeoVisualDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFillColorFieldBuilder();
        getLineColorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fillColor_ = null;
      if (fillColorBuilder_ != null) {
        fillColorBuilder_.dispose();
        fillColorBuilder_ = null;
      }
      lineColor_ = null;
      if (lineColorBuilder_ != null) {
        lineColorBuilder_.dispose();
        lineColorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.anduril.entitymanager.v1.GeoentityPubProto.internal_static_anduril_entitymanager_v1_GeoVisualDetails_descriptor;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.GeoVisualDetails getDefaultInstanceForType() {
      return com.anduril.entitymanager.v1.GeoVisualDetails.getDefaultInstance();
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.GeoVisualDetails build() {
      com.anduril.entitymanager.v1.GeoVisualDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.GeoVisualDetails buildPartial() {
      com.anduril.entitymanager.v1.GeoVisualDetails result = new com.anduril.entitymanager.v1.GeoVisualDetails(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.anduril.entitymanager.v1.GeoVisualDetails result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fillColor_ = fillColorBuilder_ == null
            ? fillColor_
            : fillColorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lineColor_ = lineColorBuilder_ == null
            ? lineColor_
            : lineColorBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.anduril.entitymanager.v1.GeoVisualDetails) {
        return mergeFrom((com.anduril.entitymanager.v1.GeoVisualDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.anduril.entitymanager.v1.GeoVisualDetails other) {
      if (other == com.anduril.entitymanager.v1.GeoVisualDetails.getDefaultInstance()) return this;
      if (other.hasFillColor()) {
        mergeFillColor(other.getFillColor());
      }
      if (other.hasLineColor()) {
        mergeLineColor(other.getLineColor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFillColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getLineColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.anduril.type.Color fillColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.anduril.type.Color, com.anduril.type.Color.Builder, com.anduril.type.ColorOrBuilder> fillColorBuilder_;
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     * @return Whether the fillColor field is set.
     */
    public boolean hasFillColor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     * @return The fillColor.
     */
    public com.anduril.type.Color getFillColor() {
      if (fillColorBuilder_ == null) {
        return fillColor_ == null ? com.anduril.type.Color.getDefaultInstance() : fillColor_;
      } else {
        return fillColorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    public Builder setFillColor(com.anduril.type.Color value) {
      if (fillColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fillColor_ = value;
      } else {
        fillColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    public Builder setFillColor(
        com.anduril.type.Color.Builder builderForValue) {
      if (fillColorBuilder_ == null) {
        fillColor_ = builderForValue.build();
      } else {
        fillColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    public Builder mergeFillColor(com.anduril.type.Color value) {
      if (fillColorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          fillColor_ != null &&
          fillColor_ != com.anduril.type.Color.getDefaultInstance()) {
          getFillColorBuilder().mergeFrom(value);
        } else {
          fillColor_ = value;
        }
      } else {
        fillColorBuilder_.mergeFrom(value);
      }
      if (fillColor_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    public Builder clearFillColor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fillColor_ = null;
      if (fillColorBuilder_ != null) {
        fillColorBuilder_.dispose();
        fillColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    public com.anduril.type.Color.Builder getFillColorBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFillColorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    public com.anduril.type.ColorOrBuilder getFillColorOrBuilder() {
      if (fillColorBuilder_ != null) {
        return fillColorBuilder_.getMessageOrBuilder();
      } else {
        return fillColor_ == null ?
            com.anduril.type.Color.getDefaultInstance() : fillColor_;
      }
    }
    /**
     * <pre>
     *A string describing the fill color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color fill_color = 1 [json_name = "fillColor"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.anduril.type.Color, com.anduril.type.Color.Builder, com.anduril.type.ColorOrBuilder> 
        getFillColorFieldBuilder() {
      if (fillColorBuilder_ == null) {
        fillColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.anduril.type.Color, com.anduril.type.Color.Builder, com.anduril.type.ColorOrBuilder>(
                getFillColor(),
                getParentForChildren(),
                isClean());
        fillColor_ = null;
      }
      return fillColorBuilder_;
    }

    private com.anduril.type.Color lineColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.anduril.type.Color, com.anduril.type.Color.Builder, com.anduril.type.ColorOrBuilder> lineColorBuilder_;
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     * @return Whether the lineColor field is set.
     */
    public boolean hasLineColor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     * @return The lineColor.
     */
    public com.anduril.type.Color getLineColor() {
      if (lineColorBuilder_ == null) {
        return lineColor_ == null ? com.anduril.type.Color.getDefaultInstance() : lineColor_;
      } else {
        return lineColorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    public Builder setLineColor(com.anduril.type.Color value) {
      if (lineColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lineColor_ = value;
      } else {
        lineColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    public Builder setLineColor(
        com.anduril.type.Color.Builder builderForValue) {
      if (lineColorBuilder_ == null) {
        lineColor_ = builderForValue.build();
      } else {
        lineColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    public Builder mergeLineColor(com.anduril.type.Color value) {
      if (lineColorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          lineColor_ != null &&
          lineColor_ != com.anduril.type.Color.getDefaultInstance()) {
          getLineColorBuilder().mergeFrom(value);
        } else {
          lineColor_ = value;
        }
      } else {
        lineColorBuilder_.mergeFrom(value);
      }
      if (lineColor_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    public Builder clearLineColor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lineColor_ = null;
      if (lineColorBuilder_ != null) {
        lineColorBuilder_.dispose();
        lineColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    public com.anduril.type.Color.Builder getLineColorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getLineColorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    public com.anduril.type.ColorOrBuilder getLineColorOrBuilder() {
      if (lineColorBuilder_ != null) {
        return lineColorBuilder_.getMessageOrBuilder();
      } else {
        return lineColor_ == null ?
            com.anduril.type.Color.getDefaultInstance() : lineColor_;
      }
    }
    /**
     * <pre>
     *A string describing the line color of a geo-entity.
     * </pre>
     *
     * <code>.anduril.type.Color line_color = 2 [json_name = "lineColor"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.anduril.type.Color, com.anduril.type.Color.Builder, com.anduril.type.ColorOrBuilder> 
        getLineColorFieldBuilder() {
      if (lineColorBuilder_ == null) {
        lineColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.anduril.type.Color, com.anduril.type.Color.Builder, com.anduril.type.ColorOrBuilder>(
                getLineColor(),
                getParentForChildren(),
                isClean());
        lineColor_ = null;
      }
      return lineColorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:anduril.entitymanager.v1.GeoVisualDetails)
  }

  // @@protoc_insertion_point(class_scope:anduril.entitymanager.v1.GeoVisualDetails)
  private static final com.anduril.entitymanager.v1.GeoVisualDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.anduril.entitymanager.v1.GeoVisualDetails();
  }

  public static com.anduril.entitymanager.v1.GeoVisualDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeoVisualDetails>
      PARSER = new com.google.protobuf.AbstractParser<GeoVisualDetails>() {
    @java.lang.Override
    public GeoVisualDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GeoVisualDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeoVisualDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.anduril.entitymanager.v1.GeoVisualDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

