// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/entitymanager/v1/entity.pub.proto

package com.anduril.entitymanager.v1;

/**
 * <pre>
 * Indicators to describe entity to consumers.
 * </pre>
 *
 * Protobuf type {@code anduril.entitymanager.v1.Indicators}
 */
public final class Indicators extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:anduril.entitymanager.v1.Indicators)
    IndicatorsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Indicators.newBuilder() to construct.
  private Indicators(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Indicators() {
    deletable_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Indicators();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.anduril.entitymanager.v1.EntityPubProto.internal_static_anduril_entitymanager_v1_Indicators_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.anduril.entitymanager.v1.EntityPubProto.internal_static_anduril_entitymanager_v1_Indicators_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.anduril.entitymanager.v1.Indicators.class, com.anduril.entitymanager.v1.Indicators.Builder.class);
  }

  public static final int SIMULATED_FIELD_NUMBER = 1;
  private com.google.protobuf.BoolValue simulated_;
  /**
   * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
   * @return Whether the simulated field is set.
   */
  @java.lang.Override
  public boolean hasSimulated() {
    return simulated_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
   * @return The simulated.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getSimulated() {
    return simulated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : simulated_;
  }
  /**
   * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getSimulatedOrBuilder() {
    return simulated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : simulated_;
  }

  public static final int EXERCISE_FIELD_NUMBER = 2;
  private com.google.protobuf.BoolValue exercise_;
  /**
   * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
   * @return Whether the exercise field is set.
   */
  @java.lang.Override
  public boolean hasExercise() {
    return exercise_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
   * @return The exercise.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getExercise() {
    return exercise_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : exercise_;
  }
  /**
   * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getExerciseOrBuilder() {
    return exercise_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : exercise_;
  }

  public static final int EMERGENCY_FIELD_NUMBER = 3;
  private com.google.protobuf.BoolValue emergency_;
  /**
   * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
   * @return Whether the emergency field is set.
   */
  @java.lang.Override
  public boolean hasEmergency() {
    return emergency_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
   * @return The emergency.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getEmergency() {
    return emergency_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : emergency_;
  }
  /**
   * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getEmergencyOrBuilder() {
    return emergency_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : emergency_;
  }

  public static final int C2_FIELD_NUMBER = 4;
  private com.google.protobuf.BoolValue c2_;
  /**
   * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
   * @return Whether the c2 field is set.
   */
  @java.lang.Override
  public boolean hasC2() {
    return c2_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
   * @return The c2.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getC2() {
    return c2_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : c2_;
  }
  /**
   * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getC2OrBuilder() {
    return c2_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : c2_;
  }

  public static final int DELETABLE_FIELD_NUMBER = 5;
  private int deletable_ = 0;
  /**
   * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
   * @return The enum numeric value on the wire for deletable.
   */
  @java.lang.Override public int getDeletableValue() {
    return deletable_;
  }
  /**
   * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
   * @return The deletable.
   */
  @java.lang.Override public com.anduril.entitymanager.v1.Deletable getDeletable() {
    com.anduril.entitymanager.v1.Deletable result = com.anduril.entitymanager.v1.Deletable.forNumber(deletable_);
    return result == null ? com.anduril.entitymanager.v1.Deletable.UNRECOGNIZED : result;
  }

  public static final int EGRESSABLE_FIELD_NUMBER = 6;
  private com.google.protobuf.BoolValue egressable_;
  /**
   * <pre>
   * Indicates the Entity should be egressed to external sources.
   * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
   * @return Whether the egressable field is set.
   */
  @java.lang.Override
  public boolean hasEgressable() {
    return egressable_ != null;
  }
  /**
   * <pre>
   * Indicates the Entity should be egressed to external sources.
   * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
   * @return The egressable.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getEgressable() {
    return egressable_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : egressable_;
  }
  /**
   * <pre>
   * Indicates the Entity should be egressed to external sources.
   * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getEgressableOrBuilder() {
    return egressable_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : egressable_;
  }

  public static final int STARRED_FIELD_NUMBER = 7;
  private com.google.protobuf.BoolValue starred_;
  /**
   * <pre>
   * A signal of arbitrary importance such that the entity should be globally marked for all users
   * </pre>
   *
   * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
   * @return Whether the starred field is set.
   */
  @java.lang.Override
  public boolean hasStarred() {
    return starred_ != null;
  }
  /**
   * <pre>
   * A signal of arbitrary importance such that the entity should be globally marked for all users
   * </pre>
   *
   * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
   * @return The starred.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getStarred() {
    return starred_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : starred_;
  }
  /**
   * <pre>
   * A signal of arbitrary importance such that the entity should be globally marked for all users
   * </pre>
   *
   * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getStarredOrBuilder() {
    return starred_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : starred_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (simulated_ != null) {
      output.writeMessage(1, getSimulated());
    }
    if (exercise_ != null) {
      output.writeMessage(2, getExercise());
    }
    if (emergency_ != null) {
      output.writeMessage(3, getEmergency());
    }
    if (c2_ != null) {
      output.writeMessage(4, getC2());
    }
    if (deletable_ != com.anduril.entitymanager.v1.Deletable.DELETABLE_INVALID.getNumber()) {
      output.writeEnum(5, deletable_);
    }
    if (egressable_ != null) {
      output.writeMessage(6, getEgressable());
    }
    if (starred_ != null) {
      output.writeMessage(7, getStarred());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (simulated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSimulated());
    }
    if (exercise_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getExercise());
    }
    if (emergency_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEmergency());
    }
    if (c2_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getC2());
    }
    if (deletable_ != com.anduril.entitymanager.v1.Deletable.DELETABLE_INVALID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, deletable_);
    }
    if (egressable_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getEgressable());
    }
    if (starred_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getStarred());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.anduril.entitymanager.v1.Indicators)) {
      return super.equals(obj);
    }
    com.anduril.entitymanager.v1.Indicators other = (com.anduril.entitymanager.v1.Indicators) obj;

    if (hasSimulated() != other.hasSimulated()) return false;
    if (hasSimulated()) {
      if (!getSimulated()
          .equals(other.getSimulated())) return false;
    }
    if (hasExercise() != other.hasExercise()) return false;
    if (hasExercise()) {
      if (!getExercise()
          .equals(other.getExercise())) return false;
    }
    if (hasEmergency() != other.hasEmergency()) return false;
    if (hasEmergency()) {
      if (!getEmergency()
          .equals(other.getEmergency())) return false;
    }
    if (hasC2() != other.hasC2()) return false;
    if (hasC2()) {
      if (!getC2()
          .equals(other.getC2())) return false;
    }
    if (deletable_ != other.deletable_) return false;
    if (hasEgressable() != other.hasEgressable()) return false;
    if (hasEgressable()) {
      if (!getEgressable()
          .equals(other.getEgressable())) return false;
    }
    if (hasStarred() != other.hasStarred()) return false;
    if (hasStarred()) {
      if (!getStarred()
          .equals(other.getStarred())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSimulated()) {
      hash = (37 * hash) + SIMULATED_FIELD_NUMBER;
      hash = (53 * hash) + getSimulated().hashCode();
    }
    if (hasExercise()) {
      hash = (37 * hash) + EXERCISE_FIELD_NUMBER;
      hash = (53 * hash) + getExercise().hashCode();
    }
    if (hasEmergency()) {
      hash = (37 * hash) + EMERGENCY_FIELD_NUMBER;
      hash = (53 * hash) + getEmergency().hashCode();
    }
    if (hasC2()) {
      hash = (37 * hash) + C2_FIELD_NUMBER;
      hash = (53 * hash) + getC2().hashCode();
    }
    hash = (37 * hash) + DELETABLE_FIELD_NUMBER;
    hash = (53 * hash) + deletable_;
    if (hasEgressable()) {
      hash = (37 * hash) + EGRESSABLE_FIELD_NUMBER;
      hash = (53 * hash) + getEgressable().hashCode();
    }
    if (hasStarred()) {
      hash = (37 * hash) + STARRED_FIELD_NUMBER;
      hash = (53 * hash) + getStarred().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.Indicators parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.Indicators parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.Indicators parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.anduril.entitymanager.v1.Indicators prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Indicators to describe entity to consumers.
   * </pre>
   *
   * Protobuf type {@code anduril.entitymanager.v1.Indicators}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:anduril.entitymanager.v1.Indicators)
      com.anduril.entitymanager.v1.IndicatorsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anduril.entitymanager.v1.EntityPubProto.internal_static_anduril_entitymanager_v1_Indicators_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anduril.entitymanager.v1.EntityPubProto.internal_static_anduril_entitymanager_v1_Indicators_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.anduril.entitymanager.v1.Indicators.class, com.anduril.entitymanager.v1.Indicators.Builder.class);
    }

    // Construct using com.anduril.entitymanager.v1.Indicators.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      simulated_ = null;
      if (simulatedBuilder_ != null) {
        simulatedBuilder_.dispose();
        simulatedBuilder_ = null;
      }
      exercise_ = null;
      if (exerciseBuilder_ != null) {
        exerciseBuilder_.dispose();
        exerciseBuilder_ = null;
      }
      emergency_ = null;
      if (emergencyBuilder_ != null) {
        emergencyBuilder_.dispose();
        emergencyBuilder_ = null;
      }
      c2_ = null;
      if (c2Builder_ != null) {
        c2Builder_.dispose();
        c2Builder_ = null;
      }
      deletable_ = 0;
      egressable_ = null;
      if (egressableBuilder_ != null) {
        egressableBuilder_.dispose();
        egressableBuilder_ = null;
      }
      starred_ = null;
      if (starredBuilder_ != null) {
        starredBuilder_.dispose();
        starredBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.anduril.entitymanager.v1.EntityPubProto.internal_static_anduril_entitymanager_v1_Indicators_descriptor;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.Indicators getDefaultInstanceForType() {
      return com.anduril.entitymanager.v1.Indicators.getDefaultInstance();
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.Indicators build() {
      com.anduril.entitymanager.v1.Indicators result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.Indicators buildPartial() {
      com.anduril.entitymanager.v1.Indicators result = new com.anduril.entitymanager.v1.Indicators(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.anduril.entitymanager.v1.Indicators result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.simulated_ = simulatedBuilder_ == null
            ? simulated_
            : simulatedBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.exercise_ = exerciseBuilder_ == null
            ? exercise_
            : exerciseBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.emergency_ = emergencyBuilder_ == null
            ? emergency_
            : emergencyBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.c2_ = c2Builder_ == null
            ? c2_
            : c2Builder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.deletable_ = deletable_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.egressable_ = egressableBuilder_ == null
            ? egressable_
            : egressableBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.starred_ = starredBuilder_ == null
            ? starred_
            : starredBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.anduril.entitymanager.v1.Indicators) {
        return mergeFrom((com.anduril.entitymanager.v1.Indicators)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.anduril.entitymanager.v1.Indicators other) {
      if (other == com.anduril.entitymanager.v1.Indicators.getDefaultInstance()) return this;
      if (other.hasSimulated()) {
        mergeSimulated(other.getSimulated());
      }
      if (other.hasExercise()) {
        mergeExercise(other.getExercise());
      }
      if (other.hasEmergency()) {
        mergeEmergency(other.getEmergency());
      }
      if (other.hasC2()) {
        mergeC2(other.getC2());
      }
      if (other.deletable_ != 0) {
        setDeletableValue(other.getDeletableValue());
      }
      if (other.hasEgressable()) {
        mergeEgressable(other.getEgressable());
      }
      if (other.hasStarred()) {
        mergeStarred(other.getStarred());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSimulatedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getExerciseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getEmergencyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getC2FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              deletable_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getEgressableFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getStarredFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.BoolValue simulated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> simulatedBuilder_;
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     * @return Whether the simulated field is set.
     */
    public boolean hasSimulated() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     * @return The simulated.
     */
    public com.google.protobuf.BoolValue getSimulated() {
      if (simulatedBuilder_ == null) {
        return simulated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : simulated_;
      } else {
        return simulatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    public Builder setSimulated(com.google.protobuf.BoolValue value) {
      if (simulatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        simulated_ = value;
      } else {
        simulatedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    public Builder setSimulated(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (simulatedBuilder_ == null) {
        simulated_ = builderForValue.build();
      } else {
        simulatedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    public Builder mergeSimulated(com.google.protobuf.BoolValue value) {
      if (simulatedBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          simulated_ != null &&
          simulated_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getSimulatedBuilder().mergeFrom(value);
        } else {
          simulated_ = value;
        }
      } else {
        simulatedBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    public Builder clearSimulated() {
      bitField0_ = (bitField0_ & ~0x00000001);
      simulated_ = null;
      if (simulatedBuilder_ != null) {
        simulatedBuilder_.dispose();
        simulatedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getSimulatedBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSimulatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getSimulatedOrBuilder() {
      if (simulatedBuilder_ != null) {
        return simulatedBuilder_.getMessageOrBuilder();
      } else {
        return simulated_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : simulated_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue simulated = 1 [json_name = "simulated"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getSimulatedFieldBuilder() {
      if (simulatedBuilder_ == null) {
        simulatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getSimulated(),
                getParentForChildren(),
                isClean());
        simulated_ = null;
      }
      return simulatedBuilder_;
    }

    private com.google.protobuf.BoolValue exercise_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> exerciseBuilder_;
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     * @return Whether the exercise field is set.
     */
    public boolean hasExercise() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     * @return The exercise.
     */
    public com.google.protobuf.BoolValue getExercise() {
      if (exerciseBuilder_ == null) {
        return exercise_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : exercise_;
      } else {
        return exerciseBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    public Builder setExercise(com.google.protobuf.BoolValue value) {
      if (exerciseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        exercise_ = value;
      } else {
        exerciseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    public Builder setExercise(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (exerciseBuilder_ == null) {
        exercise_ = builderForValue.build();
      } else {
        exerciseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    public Builder mergeExercise(com.google.protobuf.BoolValue value) {
      if (exerciseBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          exercise_ != null &&
          exercise_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getExerciseBuilder().mergeFrom(value);
        } else {
          exercise_ = value;
        }
      } else {
        exerciseBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    public Builder clearExercise() {
      bitField0_ = (bitField0_ & ~0x00000002);
      exercise_ = null;
      if (exerciseBuilder_ != null) {
        exerciseBuilder_.dispose();
        exerciseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getExerciseBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getExerciseFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getExerciseOrBuilder() {
      if (exerciseBuilder_ != null) {
        return exerciseBuilder_.getMessageOrBuilder();
      } else {
        return exercise_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : exercise_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue exercise = 2 [json_name = "exercise"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getExerciseFieldBuilder() {
      if (exerciseBuilder_ == null) {
        exerciseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getExercise(),
                getParentForChildren(),
                isClean());
        exercise_ = null;
      }
      return exerciseBuilder_;
    }

    private com.google.protobuf.BoolValue emergency_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> emergencyBuilder_;
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     * @return Whether the emergency field is set.
     */
    public boolean hasEmergency() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     * @return The emergency.
     */
    public com.google.protobuf.BoolValue getEmergency() {
      if (emergencyBuilder_ == null) {
        return emergency_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : emergency_;
      } else {
        return emergencyBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    public Builder setEmergency(com.google.protobuf.BoolValue value) {
      if (emergencyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        emergency_ = value;
      } else {
        emergencyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    public Builder setEmergency(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (emergencyBuilder_ == null) {
        emergency_ = builderForValue.build();
      } else {
        emergencyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    public Builder mergeEmergency(com.google.protobuf.BoolValue value) {
      if (emergencyBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          emergency_ != null &&
          emergency_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getEmergencyBuilder().mergeFrom(value);
        } else {
          emergency_ = value;
        }
      } else {
        emergencyBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    public Builder clearEmergency() {
      bitField0_ = (bitField0_ & ~0x00000004);
      emergency_ = null;
      if (emergencyBuilder_ != null) {
        emergencyBuilder_.dispose();
        emergencyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getEmergencyBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getEmergencyFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getEmergencyOrBuilder() {
      if (emergencyBuilder_ != null) {
        return emergencyBuilder_.getMessageOrBuilder();
      } else {
        return emergency_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : emergency_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue emergency = 3 [json_name = "emergency"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getEmergencyFieldBuilder() {
      if (emergencyBuilder_ == null) {
        emergencyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getEmergency(),
                getParentForChildren(),
                isClean());
        emergency_ = null;
      }
      return emergencyBuilder_;
    }

    private com.google.protobuf.BoolValue c2_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> c2Builder_;
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     * @return Whether the c2 field is set.
     */
    public boolean hasC2() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     * @return The c2.
     */
    public com.google.protobuf.BoolValue getC2() {
      if (c2Builder_ == null) {
        return c2_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : c2_;
      } else {
        return c2Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    public Builder setC2(com.google.protobuf.BoolValue value) {
      if (c2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        c2_ = value;
      } else {
        c2Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    public Builder setC2(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (c2Builder_ == null) {
        c2_ = builderForValue.build();
      } else {
        c2Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    public Builder mergeC2(com.google.protobuf.BoolValue value) {
      if (c2Builder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          c2_ != null &&
          c2_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getC2Builder().mergeFrom(value);
        } else {
          c2_ = value;
        }
      } else {
        c2Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    public Builder clearC2() {
      bitField0_ = (bitField0_ & ~0x00000008);
      c2_ = null;
      if (c2Builder_ != null) {
        c2Builder_.dispose();
        c2Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getC2Builder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getC2FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getC2OrBuilder() {
      if (c2Builder_ != null) {
        return c2Builder_.getMessageOrBuilder();
      } else {
        return c2_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : c2_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue c2 = 4 [json_name = "c2"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getC2FieldBuilder() {
      if (c2Builder_ == null) {
        c2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getC2(),
                getParentForChildren(),
                isClean());
        c2_ = null;
      }
      return c2Builder_;
    }

    private int deletable_ = 0;
    /**
     * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
     * @return The enum numeric value on the wire for deletable.
     */
    @java.lang.Override public int getDeletableValue() {
      return deletable_;
    }
    /**
     * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
     * @param value The enum numeric value on the wire for deletable to set.
     * @return This builder for chaining.
     */
    public Builder setDeletableValue(int value) {
      deletable_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
     * @return The deletable.
     */
    @java.lang.Override
    public com.anduril.entitymanager.v1.Deletable getDeletable() {
      com.anduril.entitymanager.v1.Deletable result = com.anduril.entitymanager.v1.Deletable.forNumber(deletable_);
      return result == null ? com.anduril.entitymanager.v1.Deletable.UNRECOGNIZED : result;
    }
    /**
     * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
     * @param value The deletable to set.
     * @return This builder for chaining.
     */
    public Builder setDeletable(com.anduril.entitymanager.v1.Deletable value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      deletable_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.Deletable deletable = 5 [json_name = "deletable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletable() {
      bitField0_ = (bitField0_ & ~0x00000010);
      deletable_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.BoolValue egressable_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> egressableBuilder_;
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     * @return Whether the egressable field is set.
     */
    public boolean hasEgressable() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     * @return The egressable.
     */
    public com.google.protobuf.BoolValue getEgressable() {
      if (egressableBuilder_ == null) {
        return egressable_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : egressable_;
      } else {
        return egressableBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder setEgressable(com.google.protobuf.BoolValue value) {
      if (egressableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        egressable_ = value;
      } else {
        egressableBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder setEgressable(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (egressableBuilder_ == null) {
        egressable_ = builderForValue.build();
      } else {
        egressableBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder mergeEgressable(com.google.protobuf.BoolValue value) {
      if (egressableBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          egressable_ != null &&
          egressable_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getEgressableBuilder().mergeFrom(value);
        } else {
          egressable_ = value;
        }
      } else {
        egressableBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder clearEgressable() {
      bitField0_ = (bitField0_ & ~0x00000020);
      egressable_ = null;
      if (egressableBuilder_ != null) {
        egressableBuilder_.dispose();
        egressableBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public com.google.protobuf.BoolValue.Builder getEgressableBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getEgressableFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getEgressableOrBuilder() {
      if (egressableBuilder_ != null) {
        return egressableBuilder_.getMessageOrBuilder();
      } else {
        return egressable_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : egressable_;
      }
    }
    /**
     * <pre>
     * Indicates the Entity should be egressed to external sources.
     * Integrations choose how the egressing happens (e.g. if an Entity needs fuzzing).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue egressable = 6 [json_name = "egressable", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getEgressableFieldBuilder() {
      if (egressableBuilder_ == null) {
        egressableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getEgressable(),
                getParentForChildren(),
                isClean());
        egressable_ = null;
      }
      return egressableBuilder_;
    }

    private com.google.protobuf.BoolValue starred_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> starredBuilder_;
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     * @return Whether the starred field is set.
     */
    public boolean hasStarred() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     * @return The starred.
     */
    public com.google.protobuf.BoolValue getStarred() {
      if (starredBuilder_ == null) {
        return starred_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : starred_;
      } else {
        return starredBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder setStarred(com.google.protobuf.BoolValue value) {
      if (starredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        starred_ = value;
      } else {
        starredBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder setStarred(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (starredBuilder_ == null) {
        starred_ = builderForValue.build();
      } else {
        starredBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder mergeStarred(com.google.protobuf.BoolValue value) {
      if (starredBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          starred_ != null &&
          starred_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getStarredBuilder().mergeFrom(value);
        } else {
          starred_ = value;
        }
      } else {
        starredBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public Builder clearStarred() {
      bitField0_ = (bitField0_ & ~0x00000040);
      starred_ = null;
      if (starredBuilder_ != null) {
        starredBuilder_.dispose();
        starredBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public com.google.protobuf.BoolValue.Builder getStarredBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getStarredFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getStarredOrBuilder() {
      if (starredBuilder_ != null) {
        return starredBuilder_.getMessageOrBuilder();
      } else {
        return starred_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : starred_;
      }
    }
    /**
     * <pre>
     * A signal of arbitrary importance such that the entity should be globally marked for all users
     * </pre>
     *
     * <code>.google.protobuf.BoolValue starred = 7 [json_name = "starred", (.anduril.entitymanager.v1.overridable) = true];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getStarredFieldBuilder() {
      if (starredBuilder_ == null) {
        starredBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getStarred(),
                getParentForChildren(),
                isClean());
        starred_ = null;
      }
      return starredBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:anduril.entitymanager.v1.Indicators)
  }

  // @@protoc_insertion_point(class_scope:anduril.entitymanager.v1.Indicators)
  private static final com.anduril.entitymanager.v1.Indicators DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.anduril.entitymanager.v1.Indicators();
  }

  public static com.anduril.entitymanager.v1.Indicators getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Indicators>
      PARSER = new com.google.protobuf.AbstractParser<Indicators>() {
    @java.lang.Override
    public Indicators parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Indicators> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Indicators> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.anduril.entitymanager.v1.Indicators getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

