// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/entitymanager/v1/signal.pub.proto

package com.anduril.entitymanager.v1;

public interface LineOfBearingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:anduril.entitymanager.v1.LineOfBearing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The direction pointing from this entity to the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.AngleOfArrival angle_of_arrival = 3 [json_name = "angleOfArrival"];</code>
   * @return Whether the angleOfArrival field is set.
   */
  boolean hasAngleOfArrival();
  /**
   * <pre>
   * The direction pointing from this entity to the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.AngleOfArrival angle_of_arrival = 3 [json_name = "angleOfArrival"];</code>
   * @return The angleOfArrival.
   */
  com.anduril.entitymanager.v1.AngleOfArrival getAngleOfArrival();
  /**
   * <pre>
   * The direction pointing from this entity to the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.AngleOfArrival angle_of_arrival = 3 [json_name = "angleOfArrival"];</code>
   */
  com.anduril.entitymanager.v1.AngleOfArrivalOrBuilder getAngleOfArrivalOrBuilder();

  /**
   * <pre>
   * The estimated distance of the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.Measurement range_estimate_m = 4 [json_name = "rangeEstimateM"];</code>
   * @return Whether the rangeEstimateM field is set.
   */
  boolean hasRangeEstimateM();
  /**
   * <pre>
   * The estimated distance of the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.Measurement range_estimate_m = 4 [json_name = "rangeEstimateM"];</code>
   * @return The rangeEstimateM.
   */
  com.anduril.entitymanager.v1.Measurement getRangeEstimateM();
  /**
   * <pre>
   * The estimated distance of the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.Measurement range_estimate_m = 4 [json_name = "rangeEstimateM"];</code>
   */
  com.anduril.entitymanager.v1.MeasurementOrBuilder getRangeEstimateMOrBuilder();

  /**
   * <pre>
   * The maximum distance of the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.Measurement max_range_m = 5 [json_name = "maxRangeM"];</code>
   * @return Whether the maxRangeM field is set.
   */
  boolean hasMaxRangeM();
  /**
   * <pre>
   * The maximum distance of the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.Measurement max_range_m = 5 [json_name = "maxRangeM"];</code>
   * @return The maxRangeM.
   */
  com.anduril.entitymanager.v1.Measurement getMaxRangeM();
  /**
   * <pre>
   * The maximum distance of the detection
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.Measurement max_range_m = 5 [json_name = "maxRangeM"];</code>
   */
  com.anduril.entitymanager.v1.MeasurementOrBuilder getMaxRangeMOrBuilder();

  com.anduril.entitymanager.v1.LineOfBearing.DetectionRangeCase getDetectionRangeCase();
}
