// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/entitymanager/v1/payloads.pub.proto
// Protobuf Java Version: 4.27.3

package com.anduril.entitymanager.v1;

/**
 * <pre>
 * The configuration for this capability, published on the CAPABILITY_TOPIC_PAYLOAD_CONFIGURATION topic id.
 * </pre>
 *
 * Protobuf type {@code anduril.entitymanager.v1.PayloadConfiguration}
 */
public final class PayloadConfiguration extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:anduril.entitymanager.v1.PayloadConfiguration)
    PayloadConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      PayloadConfiguration.class.getName());
  }
  // Use PayloadConfiguration.newBuilder() to construct.
  private PayloadConfiguration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PayloadConfiguration() {
    capabilityId_ = "";
    effectiveEnvironment_ = java.util.Collections.emptyList();
    payloadOperationalState_ = 0;
    payloadDescription_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.anduril.entitymanager.v1.PayloadsPubProto.internal_static_anduril_entitymanager_v1_PayloadConfiguration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.anduril.entitymanager.v1.PayloadsPubProto.internal_static_anduril_entitymanager_v1_PayloadConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.anduril.entitymanager.v1.PayloadConfiguration.class, com.anduril.entitymanager.v1.PayloadConfiguration.Builder.class);
  }

  public static final int CAPABILITY_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object capabilityId_ = "";
  /**
   * <pre>
   * Identifying ID for the capability.
   * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
   * </pre>
   *
   * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
   * @return The capabilityId.
   */
  @java.lang.Override
  public java.lang.String getCapabilityId() {
    java.lang.Object ref = capabilityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      capabilityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Identifying ID for the capability.
   * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
   * </pre>
   *
   * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
   * @return The bytes for capabilityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCapabilityIdBytes() {
    java.lang.Object ref = capabilityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      capabilityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_ = 0;
  /**
   * <pre>
   * The number of payloads currently available in the configuration.
   * </pre>
   *
   * <code>uint32 quantity = 4 [json_name = "quantity"];</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int EFFECTIVE_ENVIRONMENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<java.lang.Integer> effectiveEnvironment_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.anduril.ontology.v1.Environment> effectiveEnvironment_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.anduril.ontology.v1.Environment>() {
            public com.anduril.ontology.v1.Environment convert(java.lang.Integer from) {
              com.anduril.ontology.v1.Environment result = com.anduril.ontology.v1.Environment.forNumber(from);
              return result == null ? com.anduril.ontology.v1.Environment.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * The target environments the configuration is effective against.
   * </pre>
   *
   * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
   * @return A list containing the effectiveEnvironment.
   */
  @java.lang.Override
  public java.util.List<com.anduril.ontology.v1.Environment> getEffectiveEnvironmentList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.anduril.ontology.v1.Environment>(effectiveEnvironment_, effectiveEnvironment_converter_);
  }
  /**
   * <pre>
   * The target environments the configuration is effective against.
   * </pre>
   *
   * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
   * @return The count of effectiveEnvironment.
   */
  @java.lang.Override
  public int getEffectiveEnvironmentCount() {
    return effectiveEnvironment_.size();
  }
  /**
   * <pre>
   * The target environments the configuration is effective against.
   * </pre>
   *
   * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
   * @param index The index of the element to return.
   * @return The effectiveEnvironment at the given index.
   */
  @java.lang.Override
  public com.anduril.ontology.v1.Environment getEffectiveEnvironment(int index) {
    return effectiveEnvironment_converter_.convert(effectiveEnvironment_.get(index));
  }
  /**
   * <pre>
   * The target environments the configuration is effective against.
   * </pre>
   *
   * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
   * @return A list containing the enum numeric values on the wire for effectiveEnvironment.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getEffectiveEnvironmentValueList() {
    return effectiveEnvironment_;
  }
  /**
   * <pre>
   * The target environments the configuration is effective against.
   * </pre>
   *
   * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of effectiveEnvironment at the given index.
   */
  @java.lang.Override
  public int getEffectiveEnvironmentValue(int index) {
    return effectiveEnvironment_.get(index);
  }
  private int effectiveEnvironmentMemoizedSerializedSize;

  public static final int PAYLOAD_OPERATIONAL_STATE_FIELD_NUMBER = 6;
  private int payloadOperationalState_ = 0;
  /**
   * <pre>
   * The operational state of this payload.
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
   * @return The enum numeric value on the wire for payloadOperationalState.
   */
  @java.lang.Override public int getPayloadOperationalStateValue() {
    return payloadOperationalState_;
  }
  /**
   * <pre>
   * The operational state of this payload.
   * </pre>
   *
   * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
   * @return The payloadOperationalState.
   */
  @java.lang.Override public com.anduril.entitymanager.v1.PayloadOperationalState getPayloadOperationalState() {
    com.anduril.entitymanager.v1.PayloadOperationalState result = com.anduril.entitymanager.v1.PayloadOperationalState.forNumber(payloadOperationalState_);
    return result == null ? com.anduril.entitymanager.v1.PayloadOperationalState.UNRECOGNIZED : result;
  }

  public static final int PAYLOAD_DESCRIPTION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object payloadDescription_ = "";
  /**
   * <pre>
   * A human readable description of the payload
   * </pre>
   *
   * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
   * @return The payloadDescription.
   */
  @java.lang.Override
  public java.lang.String getPayloadDescription() {
    java.lang.Object ref = payloadDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payloadDescription_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A human readable description of the payload
   * </pre>
   *
   * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
   * @return The bytes for payloadDescription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPayloadDescriptionBytes() {
    java.lang.Object ref = payloadDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payloadDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(capabilityId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, capabilityId_);
    }
    if (quantity_ != 0) {
      output.writeUInt32(4, quantity_);
    }
    if (getEffectiveEnvironmentList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(effectiveEnvironmentMemoizedSerializedSize);
    }
    for (int i = 0; i < effectiveEnvironment_.size(); i++) {
      output.writeEnumNoTag(effectiveEnvironment_.get(i));
    }
    if (payloadOperationalState_ != com.anduril.entitymanager.v1.PayloadOperationalState.PAYLOAD_OPERATIONAL_STATE_INVALID.getNumber()) {
      output.writeEnum(6, payloadOperationalState_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payloadDescription_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, payloadDescription_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(capabilityId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, capabilityId_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, quantity_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < effectiveEnvironment_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(effectiveEnvironment_.get(i));
      }
      size += dataSize;
      if (!getEffectiveEnvironmentList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }effectiveEnvironmentMemoizedSerializedSize = dataSize;
    }
    if (payloadOperationalState_ != com.anduril.entitymanager.v1.PayloadOperationalState.PAYLOAD_OPERATIONAL_STATE_INVALID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, payloadOperationalState_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payloadDescription_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, payloadDescription_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.anduril.entitymanager.v1.PayloadConfiguration)) {
      return super.equals(obj);
    }
    com.anduril.entitymanager.v1.PayloadConfiguration other = (com.anduril.entitymanager.v1.PayloadConfiguration) obj;

    if (!getCapabilityId()
        .equals(other.getCapabilityId())) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!effectiveEnvironment_.equals(other.effectiveEnvironment_)) return false;
    if (payloadOperationalState_ != other.payloadOperationalState_) return false;
    if (!getPayloadDescription()
        .equals(other.getPayloadDescription())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAPABILITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCapabilityId().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    if (getEffectiveEnvironmentCount() > 0) {
      hash = (37 * hash) + EFFECTIVE_ENVIRONMENT_FIELD_NUMBER;
      hash = (53 * hash) + effectiveEnvironment_.hashCode();
    }
    hash = (37 * hash) + PAYLOAD_OPERATIONAL_STATE_FIELD_NUMBER;
    hash = (53 * hash) + payloadOperationalState_;
    hash = (37 * hash) + PAYLOAD_DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getPayloadDescription().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.anduril.entitymanager.v1.PayloadConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.anduril.entitymanager.v1.PayloadConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.PayloadConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.anduril.entitymanager.v1.PayloadConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The configuration for this capability, published on the CAPABILITY_TOPIC_PAYLOAD_CONFIGURATION topic id.
   * </pre>
   *
   * Protobuf type {@code anduril.entitymanager.v1.PayloadConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:anduril.entitymanager.v1.PayloadConfiguration)
      com.anduril.entitymanager.v1.PayloadConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anduril.entitymanager.v1.PayloadsPubProto.internal_static_anduril_entitymanager_v1_PayloadConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anduril.entitymanager.v1.PayloadsPubProto.internal_static_anduril_entitymanager_v1_PayloadConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.anduril.entitymanager.v1.PayloadConfiguration.class, com.anduril.entitymanager.v1.PayloadConfiguration.Builder.class);
    }

    // Construct using com.anduril.entitymanager.v1.PayloadConfiguration.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      capabilityId_ = "";
      quantity_ = 0;
      effectiveEnvironment_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      payloadOperationalState_ = 0;
      payloadDescription_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.anduril.entitymanager.v1.PayloadsPubProto.internal_static_anduril_entitymanager_v1_PayloadConfiguration_descriptor;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.PayloadConfiguration getDefaultInstanceForType() {
      return com.anduril.entitymanager.v1.PayloadConfiguration.getDefaultInstance();
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.PayloadConfiguration build() {
      com.anduril.entitymanager.v1.PayloadConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.PayloadConfiguration buildPartial() {
      com.anduril.entitymanager.v1.PayloadConfiguration result = new com.anduril.entitymanager.v1.PayloadConfiguration(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.anduril.entitymanager.v1.PayloadConfiguration result) {
      if (((bitField0_ & 0x00000004) != 0)) {
        effectiveEnvironment_ = java.util.Collections.unmodifiableList(effectiveEnvironment_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.effectiveEnvironment_ = effectiveEnvironment_;
    }

    private void buildPartial0(com.anduril.entitymanager.v1.PayloadConfiguration result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.capabilityId_ = capabilityId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.payloadOperationalState_ = payloadOperationalState_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.payloadDescription_ = payloadDescription_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.anduril.entitymanager.v1.PayloadConfiguration) {
        return mergeFrom((com.anduril.entitymanager.v1.PayloadConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.anduril.entitymanager.v1.PayloadConfiguration other) {
      if (other == com.anduril.entitymanager.v1.PayloadConfiguration.getDefaultInstance()) return this;
      if (!other.getCapabilityId().isEmpty()) {
        capabilityId_ = other.capabilityId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (!other.effectiveEnvironment_.isEmpty()) {
        if (effectiveEnvironment_.isEmpty()) {
          effectiveEnvironment_ = other.effectiveEnvironment_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureEffectiveEnvironmentIsMutable();
          effectiveEnvironment_.addAll(other.effectiveEnvironment_);
        }
        onChanged();
      }
      if (other.payloadOperationalState_ != 0) {
        setPayloadOperationalStateValue(other.getPayloadOperationalStateValue());
      }
      if (!other.getPayloadDescription().isEmpty()) {
        payloadDescription_ = other.payloadDescription_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              capabilityId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 32: {
              quantity_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 32
            case 40: {
              int tmpRaw = input.readEnum();
              ensureEffectiveEnvironmentIsMutable();
              effectiveEnvironment_.add(tmpRaw);
              break;
            } // case 40
            case 42: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureEffectiveEnvironmentIsMutable();
                effectiveEnvironment_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 42
            case 48: {
              payloadOperationalState_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 48
            case 58: {
              payloadDescription_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object capabilityId_ = "";
    /**
     * <pre>
     * Identifying ID for the capability.
     * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
     * </pre>
     *
     * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
     * @return The capabilityId.
     */
    public java.lang.String getCapabilityId() {
      java.lang.Object ref = capabilityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        capabilityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Identifying ID for the capability.
     * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
     * </pre>
     *
     * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
     * @return The bytes for capabilityId.
     */
    public com.google.protobuf.ByteString
        getCapabilityIdBytes() {
      java.lang.Object ref = capabilityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        capabilityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Identifying ID for the capability.
     * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
     * </pre>
     *
     * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
     * @param value The capabilityId to set.
     * @return This builder for chaining.
     */
    public Builder setCapabilityId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      capabilityId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifying ID for the capability.
     * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
     * </pre>
     *
     * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCapabilityId() {
      capabilityId_ = getDefaultInstance().getCapabilityId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifying ID for the capability.
     * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
     * </pre>
     *
     * <code>string capability_id = 1 [json_name = "capabilityId"];</code>
     * @param value The bytes for capabilityId to set.
     * @return This builder for chaining.
     */
    public Builder setCapabilityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      capabilityId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <pre>
     * The number of payloads currently available in the configuration.
     * </pre>
     *
     * <code>uint32 quantity = 4 [json_name = "quantity"];</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <pre>
     * The number of payloads currently available in the configuration.
     * </pre>
     *
     * <code>uint32 quantity = 4 [json_name = "quantity"];</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {

      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of payloads currently available in the configuration.
     * </pre>
     *
     * <code>uint32 quantity = 4 [json_name = "quantity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000002);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> effectiveEnvironment_ =
      java.util.Collections.emptyList();
    private void ensureEffectiveEnvironmentIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        effectiveEnvironment_ = new java.util.ArrayList<java.lang.Integer>(effectiveEnvironment_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @return A list containing the effectiveEnvironment.
     */
    public java.util.List<com.anduril.ontology.v1.Environment> getEffectiveEnvironmentList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.anduril.ontology.v1.Environment>(effectiveEnvironment_, effectiveEnvironment_converter_);
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @return The count of effectiveEnvironment.
     */
    public int getEffectiveEnvironmentCount() {
      return effectiveEnvironment_.size();
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param index The index of the element to return.
     * @return The effectiveEnvironment at the given index.
     */
    public com.anduril.ontology.v1.Environment getEffectiveEnvironment(int index) {
      return effectiveEnvironment_converter_.convert(effectiveEnvironment_.get(index));
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param index The index to set the value at.
     * @param value The effectiveEnvironment to set.
     * @return This builder for chaining.
     */
    public Builder setEffectiveEnvironment(
        int index, com.anduril.ontology.v1.Environment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEffectiveEnvironmentIsMutable();
      effectiveEnvironment_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param value The effectiveEnvironment to add.
     * @return This builder for chaining.
     */
    public Builder addEffectiveEnvironment(com.anduril.ontology.v1.Environment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEffectiveEnvironmentIsMutable();
      effectiveEnvironment_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param values The effectiveEnvironment to add.
     * @return This builder for chaining.
     */
    public Builder addAllEffectiveEnvironment(
        java.lang.Iterable<? extends com.anduril.ontology.v1.Environment> values) {
      ensureEffectiveEnvironmentIsMutable();
      for (com.anduril.ontology.v1.Environment value : values) {
        effectiveEnvironment_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEffectiveEnvironment() {
      effectiveEnvironment_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @return A list containing the enum numeric values on the wire for effectiveEnvironment.
     */
    public java.util.List<java.lang.Integer>
    getEffectiveEnvironmentValueList() {
      return java.util.Collections.unmodifiableList(effectiveEnvironment_);
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of effectiveEnvironment at the given index.
     */
    public int getEffectiveEnvironmentValue(int index) {
      return effectiveEnvironment_.get(index);
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for effectiveEnvironment to set.
     * @return This builder for chaining.
     */
    public Builder setEffectiveEnvironmentValue(
        int index, int value) {
      ensureEffectiveEnvironmentIsMutable();
      effectiveEnvironment_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param value The enum numeric value on the wire for effectiveEnvironment to add.
     * @return This builder for chaining.
     */
    public Builder addEffectiveEnvironmentValue(int value) {
      ensureEffectiveEnvironmentIsMutable();
      effectiveEnvironment_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The target environments the configuration is effective against.
     * </pre>
     *
     * <code>repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];</code>
     * @param values The enum numeric values on the wire for effectiveEnvironment to add.
     * @return This builder for chaining.
     */
    public Builder addAllEffectiveEnvironmentValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureEffectiveEnvironmentIsMutable();
      for (int value : values) {
        effectiveEnvironment_.add(value);
      }
      onChanged();
      return this;
    }

    private int payloadOperationalState_ = 0;
    /**
     * <pre>
     * The operational state of this payload.
     * </pre>
     *
     * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
     * @return The enum numeric value on the wire for payloadOperationalState.
     */
    @java.lang.Override public int getPayloadOperationalStateValue() {
      return payloadOperationalState_;
    }
    /**
     * <pre>
     * The operational state of this payload.
     * </pre>
     *
     * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
     * @param value The enum numeric value on the wire for payloadOperationalState to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadOperationalStateValue(int value) {
      payloadOperationalState_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The operational state of this payload.
     * </pre>
     *
     * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
     * @return The payloadOperationalState.
     */
    @java.lang.Override
    public com.anduril.entitymanager.v1.PayloadOperationalState getPayloadOperationalState() {
      com.anduril.entitymanager.v1.PayloadOperationalState result = com.anduril.entitymanager.v1.PayloadOperationalState.forNumber(payloadOperationalState_);
      return result == null ? com.anduril.entitymanager.v1.PayloadOperationalState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The operational state of this payload.
     * </pre>
     *
     * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
     * @param value The payloadOperationalState to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadOperationalState(com.anduril.entitymanager.v1.PayloadOperationalState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      payloadOperationalState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The operational state of this payload.
     * </pre>
     *
     * <code>.anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadOperationalState() {
      bitField0_ = (bitField0_ & ~0x00000008);
      payloadOperationalState_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object payloadDescription_ = "";
    /**
     * <pre>
     * A human readable description of the payload
     * </pre>
     *
     * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
     * @return The payloadDescription.
     */
    public java.lang.String getPayloadDescription() {
      java.lang.Object ref = payloadDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payloadDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A human readable description of the payload
     * </pre>
     *
     * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
     * @return The bytes for payloadDescription.
     */
    public com.google.protobuf.ByteString
        getPayloadDescriptionBytes() {
      java.lang.Object ref = payloadDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payloadDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A human readable description of the payload
     * </pre>
     *
     * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
     * @param value The payloadDescription to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      payloadDescription_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human readable description of the payload
     * </pre>
     *
     * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadDescription() {
      payloadDescription_ = getDefaultInstance().getPayloadDescription();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human readable description of the payload
     * </pre>
     *
     * <code>string payload_description = 7 [json_name = "payloadDescription"];</code>
     * @param value The bytes for payloadDescription to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payloadDescription_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:anduril.entitymanager.v1.PayloadConfiguration)
  }

  // @@protoc_insertion_point(class_scope:anduril.entitymanager.v1.PayloadConfiguration)
  private static final com.anduril.entitymanager.v1.PayloadConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.anduril.entitymanager.v1.PayloadConfiguration();
  }

  public static com.anduril.entitymanager.v1.PayloadConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PayloadConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<PayloadConfiguration>() {
    @java.lang.Override
    public PayloadConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PayloadConfiguration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PayloadConfiguration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.anduril.entitymanager.v1.PayloadConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

