// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/entitymanager/v1/filter.pub.proto
// Protobuf Java Version: 4.27.3

package com.anduril.entitymanager.v1;

/**
 * <pre>
 * The RangeType represents a numeric range.
 * Whether endpoints are included are based on the comparator used.
 * Both endpoints must be of the same numeric type.
 * </pre>
 *
 * Protobuf type {@code anduril.entitymanager.v1.RangeType}
 */
public final class RangeType extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:anduril.entitymanager.v1.RangeType)
    RangeTypeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      RangeType.class.getName());
  }
  // Use RangeType.newBuilder() to construct.
  private RangeType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RangeType() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.anduril.entitymanager.v1.FilterPubProto.internal_static_anduril_entitymanager_v1_RangeType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.anduril.entitymanager.v1.FilterPubProto.internal_static_anduril_entitymanager_v1_RangeType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.anduril.entitymanager.v1.RangeType.class, com.anduril.entitymanager.v1.RangeType.Builder.class);
  }

  private int bitField0_;
  public static final int START_FIELD_NUMBER = 1;
  private com.anduril.entitymanager.v1.NumericType start_;
  /**
   * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  @java.lang.Override
  public com.anduril.entitymanager.v1.NumericType getStart() {
    return start_ == null ? com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : start_;
  }
  /**
   * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
   */
  @java.lang.Override
  public com.anduril.entitymanager.v1.NumericTypeOrBuilder getStartOrBuilder() {
    return start_ == null ? com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : start_;
  }

  public static final int END_FIELD_NUMBER = 2;
  private com.anduril.entitymanager.v1.NumericType end_;
  /**
   * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
   * @return Whether the end field is set.
   */
  @java.lang.Override
  public boolean hasEnd() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
   * @return The end.
   */
  @java.lang.Override
  public com.anduril.entitymanager.v1.NumericType getEnd() {
    return end_ == null ? com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : end_;
  }
  /**
   * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
   */
  @java.lang.Override
  public com.anduril.entitymanager.v1.NumericTypeOrBuilder getEndOrBuilder() {
    return end_ == null ? com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : end_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStart());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getEnd());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStart());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEnd());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.anduril.entitymanager.v1.RangeType)) {
      return super.equals(obj);
    }
    com.anduril.entitymanager.v1.RangeType other = (com.anduril.entitymanager.v1.RangeType) obj;

    if (hasStart() != other.hasStart()) return false;
    if (hasStart()) {
      if (!getStart()
          .equals(other.getStart())) return false;
    }
    if (hasEnd() != other.hasEnd()) return false;
    if (hasEnd()) {
      if (!getEnd()
          .equals(other.getEnd())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStart()) {
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
    }
    if (hasEnd()) {
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.anduril.entitymanager.v1.RangeType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.anduril.entitymanager.v1.RangeType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.anduril.entitymanager.v1.RangeType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.anduril.entitymanager.v1.RangeType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The RangeType represents a numeric range.
   * Whether endpoints are included are based on the comparator used.
   * Both endpoints must be of the same numeric type.
   * </pre>
   *
   * Protobuf type {@code anduril.entitymanager.v1.RangeType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:anduril.entitymanager.v1.RangeType)
      com.anduril.entitymanager.v1.RangeTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anduril.entitymanager.v1.FilterPubProto.internal_static_anduril_entitymanager_v1_RangeType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anduril.entitymanager.v1.FilterPubProto.internal_static_anduril_entitymanager_v1_RangeType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.anduril.entitymanager.v1.RangeType.class, com.anduril.entitymanager.v1.RangeType.Builder.class);
    }

    // Construct using com.anduril.entitymanager.v1.RangeType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getStartFieldBuilder();
        getEndFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      start_ = null;
      if (startBuilder_ != null) {
        startBuilder_.dispose();
        startBuilder_ = null;
      }
      end_ = null;
      if (endBuilder_ != null) {
        endBuilder_.dispose();
        endBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.anduril.entitymanager.v1.FilterPubProto.internal_static_anduril_entitymanager_v1_RangeType_descriptor;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.RangeType getDefaultInstanceForType() {
      return com.anduril.entitymanager.v1.RangeType.getDefaultInstance();
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.RangeType build() {
      com.anduril.entitymanager.v1.RangeType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.anduril.entitymanager.v1.RangeType buildPartial() {
      com.anduril.entitymanager.v1.RangeType result = new com.anduril.entitymanager.v1.RangeType(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.anduril.entitymanager.v1.RangeType result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.start_ = startBuilder_ == null
            ? start_
            : startBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.end_ = endBuilder_ == null
            ? end_
            : endBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.anduril.entitymanager.v1.RangeType) {
        return mergeFrom((com.anduril.entitymanager.v1.RangeType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.anduril.entitymanager.v1.RangeType other) {
      if (other == com.anduril.entitymanager.v1.RangeType.getDefaultInstance()) return this;
      if (other.hasStart()) {
        mergeStart(other.getStart());
      }
      if (other.hasEnd()) {
        mergeEnd(other.getEnd());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getEndFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.anduril.entitymanager.v1.NumericType start_;
    private com.google.protobuf.SingleFieldBuilder<
        com.anduril.entitymanager.v1.NumericType, com.anduril.entitymanager.v1.NumericType.Builder, com.anduril.entitymanager.v1.NumericTypeOrBuilder> startBuilder_;
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     * @return Whether the start field is set.
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     * @return The start.
     */
    public com.anduril.entitymanager.v1.NumericType getStart() {
      if (startBuilder_ == null) {
        return start_ == null ? com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : start_;
      } else {
        return startBuilder_.getMessage();
      }
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    public Builder setStart(com.anduril.entitymanager.v1.NumericType value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        start_ = value;
      } else {
        startBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    public Builder setStart(
        com.anduril.entitymanager.v1.NumericType.Builder builderForValue) {
      if (startBuilder_ == null) {
        start_ = builderForValue.build();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    public Builder mergeStart(com.anduril.entitymanager.v1.NumericType value) {
      if (startBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          start_ != null &&
          start_ != com.anduril.entitymanager.v1.NumericType.getDefaultInstance()) {
          getStartBuilder().mergeFrom(value);
        } else {
          start_ = value;
        }
      } else {
        startBuilder_.mergeFrom(value);
      }
      if (start_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000001);
      start_ = null;
      if (startBuilder_ != null) {
        startBuilder_.dispose();
        startBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    public com.anduril.entitymanager.v1.NumericType.Builder getStartBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    public com.anduril.entitymanager.v1.NumericTypeOrBuilder getStartOrBuilder() {
      if (startBuilder_ != null) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        return start_ == null ?
            com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : start_;
      }
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType start = 1 [json_name = "start"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.anduril.entitymanager.v1.NumericType, com.anduril.entitymanager.v1.NumericType.Builder, com.anduril.entitymanager.v1.NumericTypeOrBuilder> 
        getStartFieldBuilder() {
      if (startBuilder_ == null) {
        startBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.anduril.entitymanager.v1.NumericType, com.anduril.entitymanager.v1.NumericType.Builder, com.anduril.entitymanager.v1.NumericTypeOrBuilder>(
                getStart(),
                getParentForChildren(),
                isClean());
        start_ = null;
      }
      return startBuilder_;
    }

    private com.anduril.entitymanager.v1.NumericType end_;
    private com.google.protobuf.SingleFieldBuilder<
        com.anduril.entitymanager.v1.NumericType, com.anduril.entitymanager.v1.NumericType.Builder, com.anduril.entitymanager.v1.NumericTypeOrBuilder> endBuilder_;
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     * @return Whether the end field is set.
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     * @return The end.
     */
    public com.anduril.entitymanager.v1.NumericType getEnd() {
      if (endBuilder_ == null) {
        return end_ == null ? com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : end_;
      } else {
        return endBuilder_.getMessage();
      }
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    public Builder setEnd(com.anduril.entitymanager.v1.NumericType value) {
      if (endBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        end_ = value;
      } else {
        endBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    public Builder setEnd(
        com.anduril.entitymanager.v1.NumericType.Builder builderForValue) {
      if (endBuilder_ == null) {
        end_ = builderForValue.build();
      } else {
        endBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    public Builder mergeEnd(com.anduril.entitymanager.v1.NumericType value) {
      if (endBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          end_ != null &&
          end_ != com.anduril.entitymanager.v1.NumericType.getDefaultInstance()) {
          getEndBuilder().mergeFrom(value);
        } else {
          end_ = value;
        }
      } else {
        endBuilder_.mergeFrom(value);
      }
      if (end_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    public Builder clearEnd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      end_ = null;
      if (endBuilder_ != null) {
        endBuilder_.dispose();
        endBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    public com.anduril.entitymanager.v1.NumericType.Builder getEndBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    public com.anduril.entitymanager.v1.NumericTypeOrBuilder getEndOrBuilder() {
      if (endBuilder_ != null) {
        return endBuilder_.getMessageOrBuilder();
      } else {
        return end_ == null ?
            com.anduril.entitymanager.v1.NumericType.getDefaultInstance() : end_;
      }
    }
    /**
     * <code>.anduril.entitymanager.v1.NumericType end = 2 [json_name = "end"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.anduril.entitymanager.v1.NumericType, com.anduril.entitymanager.v1.NumericType.Builder, com.anduril.entitymanager.v1.NumericTypeOrBuilder> 
        getEndFieldBuilder() {
      if (endBuilder_ == null) {
        endBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.anduril.entitymanager.v1.NumericType, com.anduril.entitymanager.v1.NumericType.Builder, com.anduril.entitymanager.v1.NumericTypeOrBuilder>(
                getEnd(),
                getParentForChildren(),
                isClean());
        end_ = null;
      }
      return endBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:anduril.entitymanager.v1.RangeType)
  }

  // @@protoc_insertion_point(class_scope:anduril.entitymanager.v1.RangeType)
  private static final com.anduril.entitymanager.v1.RangeType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.anduril.entitymanager.v1.RangeType();
  }

  public static com.anduril.entitymanager.v1.RangeType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RangeType>
      PARSER = new com.google.protobuf.AbstractParser<RangeType>() {
    @java.lang.Override
    public RangeType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RangeType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RangeType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.anduril.entitymanager.v1.RangeType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

