name: Bump version
on:
  pull-request:
    types: [opened]
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Bump Version
      id: bump
      uses: Plugily-Projects/version-bump-action@v9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-version-bump: true
